version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8084:8084"
    environment:
      - DJANGO_SETTINGS_MODULE=recipefinder.settings
      - DEBUG=1
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn recipefinder.wsgi:application --bind 0.0.0.0:8084 --timeout 120 --workers 4"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped